name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local.properties
      run: |
        echo "CLARITY_ID=${{ secrets.CLARITY_ID }}" >> local.properties
        echo "KAKAO_APP_KEY=${{ secrets.KAKAO_APP_KEY }}" >> local.properties
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
        echo "KAKAO_HOST_SCHEME=${{ secrets.KAKAO_HOST_SCHEME }}" >> local.properties
        echo "FAQ_URL=${{ secrets.FAQ_URL }}" >> local.properties
        echo "NOTICE_URL=${{ secrets.NOTICE_URL }}" >> local.properties
    - name: Build with Gradle
      run: ./gradlew build
